config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from stackbase.models import Question
from django.http import HttpResponse
from killgpt.views import TextInputView
info_dict = {
    'queryset': Question.objects.all(),
    'date_field': 'pub_date',
}


urlpatterns = [
    path("", include("stackbase.urls"), name="stackbase"),
    path("AI/", TextInputView, name='AI'),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("hintshare.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("#", TemplateView.as_view(template_name="pages/about.html"), name="profile"),
    path('sitemap.xml', sitemap,
        {'sitemaps': {'questions': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hintshare/users/urls.py
from django.urls import path

from hintshare.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

stackbase/urls.py
import sys
sys.path.append("..") 
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from hintshare.sitemaps import StaticViewSitemap, ArticleSitemap
from . import views
from django.http import HttpResponse

app_name = "stackbase"

sitemaps = {
    'static': StaticViewSitemap,
    'questions':ArticleSitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    # CRUD Function
    path("questions/", views.QuestionListView.as_view(), name="question-lists"),
    path("questions/new/", views.QuestionCreateView.as_view(), name="question-create"),
    path(
        "questions/<int:pk>/",
        views.QuestionDetailView.as_view(),
        name="question-detail",
    ),
    path(
        "questions/<int:pk>/update/",
        views.QuestionUpdateView.as_view(),
        name="question-update",
    ),
    path(
        "questions/<int:pk>/delete/",
        views.QuestionDeleteView.as_view(),
        name="question-delete",
    ),
    path(
        "questions/<int:pk>/comment/",
        views.AddCommentView.as_view(),
        name="question-comment",
    ),
    path("like/<int:pk>", views.like_view, name="like_post"),
    path("like/<int:pk>/<int:id>", views.comment_like_view, name="like_comment"),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
   
]

hintshare/users/models.py
from ast import BinOp
from sched import scheduler
from django.core.files.storage import default_storage as storage
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, ImageField, TextField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from PIL import Image

choices = [("s12", "student grade 12"), ("s11", "student grade 11"), ("t", "teacher")]


class User(AbstractUser):
    """
    Default custom user model for hintshare.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    secondary_email = EmailField(null=True, blank=True)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    bio = TextField(
        _("A quick description of who you are."),
        blank=True,
        max_length=255,
    )
    HL = CharField(_("Your HLs"), blank=True, max_length=255)
    SL = CharField(_("Your SLs"), blank=True, max_length=255)
    Role = CharField(
        _("Role: teacher, student_11, or student_12?"), blank=True, max_length=255
    )

    Image = ImageField(default="default.jpg", upload_to="profile_pic")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(storage.open(self.Image.name))
        img = img.convert('RGB')
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            fh = storage.open(self.Image.name, "wb")
            format = 'jpeg'  # You need to set the correct image format here
            img.save(fh, format)
            fh.close()

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

hintshare/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from allauth.account.utils import has_verified_email, send_email_confirmation
User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

    fields = [
        "bio",
        "Image",
    ]

    widgets = {
        "Image": forms.FileInput(attrs={"class": "input-image-control"}),
    }

    def clean_email(self):
        data = self.cleaned_data["email"]

        if "@surreyschools.ca" not in data:  # any check you need
            # if "@gmail.com" in data:
            #     return data
            raise forms.ValidationError("Must be a surreyschools account")
        # elif "@gmail.com" not in data:  # any check you need
        #     raise forms.ValidationError("Must be a Gmail account")
       
        return data

    class Meta:
        model = User
        exclude = ("user",)


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

hintshare/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.forms import ValidationError
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    # email = object.email
    # email_str = f"https://mail.google.com/mail/?view=cm&fs=1&to=someone@example.com&su=SUBJECT&body=BODY&bcc={email}"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = "nothing"

        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["secondary_email","name", "bio", "Image", "HL", "SL", "Role"]
    success_message = _("Information successfully updated")

    def clean(self):
        data = self.cleaned_data["secondary_email"]
        if "@gmail.com" in data:
            print('gmail')
            return data
    
        elif "@yahoo.com" in data:
            print('yhoo')
            return data
        elif "@hotmail.com" in data:  # any check you need
           print('hot')
           return data
        else:
            print("nothing")
            raise ValidationError("Must be a surreyschools or gmail account")
        return data
    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

hintshare/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
{% if object.name %}
<style>
  body {
    background-color: #000000
}

.padding {
    padding: 3rem !important;
    margin-left: 200px
}

.card-img-top{
    height:300px;
}

.card-no-border .card {
    border-color: #d7dfe3;
    border-radius: 4px;
    margin-bottom: 30px;
    -webkit-box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.05);
    box-shadow: 0px 5px 20px rgba(0, 0, 0, 0.05)
}

.card-body {
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    padding: 1.25rem
}

.pro-img {
    margin-top: -80px;
    margin-bottom: 20px
}

.little-profile .pro-img img {
    width: 128px;
    height: 128px;
    -webkit-box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
    border-radius: 100%
}

html body .m-b-0 {
    margin-bottom: 0px
}

h3 {
    line-height: 30px;
    font-size: 21px
}

.btn-rounded.btn-md {
    padding: 12px 35px;
    font-size: 16px
}

html body .m-t-10 {
    margin-top: 10px
}

.btn-primary,
.btn-primary.disabled {
    background: #7460ee;
    border: 1px solid #7460ee;
    -webkit-box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
    box-shadow: 0 2px 2px 0 rgba(116, 96, 238, 0.14), 0 3px 1px -2px rgba(116, 96, 238, 0.2), 0 1px 5px 0 rgba(116, 96, 238, 0.12);
    -webkit-transition: 0.2s ease-in;
    -o-transition: 0.2s ease-in;
    transition: 0.2s ease-in
}

.btn-rounded {
    border-radius: 60px;
    padding: 7px 18px
}

.m-t-20 {
    margin-top: 20px
}

.text-center {
    text-align: center !important
}

h1,
h2,
h3,
h4,
h5,
h6 {
    color: #455a64;
    font-family: "Poppins", sans-serif;
    font-weight: 400
}

p {
    margin-top: 0;
    margin-bottom: 1rem
}
</style>
<body  style ='background: linear-gradient(to right, #000000 0%, #283295 100%)'>
    <div class="container py-5">
        <div class ='col-md-6 offset-md-3 py-5 bg-white rounded border'>
            <h1 class = 'py-1 display-1 m-5 ' style="color: #4154F1;"> Profile</h1>

            <div class="d-flex height-50 justify-content-center align-items-center flex-column py-4">
                <img src="{{ object.Image.url }}" class="img-fluid roundedcol-lg-6 pd-3 img-thumbnail " alt="...">
                <hr>
                <h3 class="m-b-0">{{ object.name }}</h3>

                <p>{{ object.bio }}</p>
                <p>{{ object.email }}</p>
                <p>{{object.secondary_email}}</p>
                <a href= "https://mail.google.com/mail/?view=cm&fs=1&to=someone@example.com&su=SUBJECT&body=BODY&bcc={{obejct.email}}" class="btn btn-primary" type="button">Contact</a>
                <hr>

            </div>
            <div class="row text-center m-t-20">
                <div class="col-lg-4 col-md-4 m-t-20">
                    <h3 class="m-b-0 font-light">HL</h3><small>{{object.HL}}</small>
                </div>
                <div class="col-lg-4 col-md-4 m-t-20">
                    <h3 class="m-b-0 font-light">SL</h3><small>{{object.SL}}</small>
                </div>
                <div class="col-lg-4 col-md-4 m-t-20">
                    <h3 class="m-b-0 font-light">Role</h3><small>{{object.Role}}</small>
                </div>
            </div>
            {% if object == request.user%}
            <div class="d-flex height-50 justify-content-center align-items-center flex-column py-4">
                <a class="btn btn-primary btn-lg btn-block" style="width:30%;" href="{% url 'users:update' %}" role="button">My Info</a>

            </div>


             {%endif%}

            </div>
        </div>
</div>
</body>

{%else%}
    {% if object == request.user%}

    <body  style ='background: linear-gradient(to left, #ffffff 0%, #4154F1 100%)'>
        <div class="container py-5">
            <div class ='col-md-6 offset-md-3 py-5 bg-white rounded border'>
                <h1 class = 'py-4 display-1 m-5 ' style="color: #4154F1;"> Input<span class="text-black" id='Titlefont'> Your Profile</h1>
                <img src="{%static 'images/minion.jpeg'%}" class="img-fluid col-lg-6 offset-md-3" alt="...">

                <div class= 'container py-5 px-3'>
                    <div class="d-grid gap-2">
                        <a href="{% url 'users:update' %}"  class="btn btn-primary" type="button">Make Profile</a>

                    </div>


                </div>
            </div>
    </div>
    </body>
{%else%}

    <body  style ='background: linear-gradient(to left, #ffffff 0%, #4154F1 100%)'>
        <div class="container py-5">
            <div class ='col-md-6 offset-md-3 py-5 bg-white rounded border'>
                <h1 class = 'py-4 display-1 m-5 ' style="color: #4154F1;"> Profile<span class="text-black" id='Titlefont'> Under Construction</h1>
                <img src="{%static 'images/construction.jpeg'%}" class="img-fluid col-lg-6 offset-md-3" alt="...">

                <div class= 'container py-5 px-3'>
                    <div class="d-grid gap-2">
                        <a href="{% url 'stackbase:question-lists' %}"  class="btn btn-primary" type="button">Back To Questions</a>

                    </div>


                </div>
            </div>
    </div>
    </body>
{% endif %}
{% endif %}



{% endblock content %}

hintshare/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<main role="main" style="background: linear-gradient(to top, #012970 0%,  #454343 100%)">
  <div class="container py-4">

  </div>
  <div class="container col-md-4 offset-md-4 rounded p-4 bg-light pt-4 ">
    <h1 style="color:#012970">{{ user.username }}</h1>
    <form class="form-horizontal" enctype="multipart/form-data" method="post" action="{% url 'users:update' %}">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </div>
    </form>
  </div>
  <div class="container py-4">

  </div>
</main>
{% endblock %}