config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from stackbase.models import Question
from django.http import HttpResponse
from killgpt.views import TextInputView
info_dict = {
    'queryset': Question.objects.all(),
    'date_field': 'pub_date',
}


urlpatterns = [
    path("", include("stackbase.urls"), name="stackbase"),
    path("AI/", TextInputView, name='AI'),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("hintshare.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("#", TemplateView.as_view(template_name="pages/about.html"), name="profile"),
    path('sitemap.xml', sitemap,
        {'sitemaps': {'questions': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hintshare/users/urls.py
from django.urls import path

from hintshare.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

stackbase/urls.py
import sys
sys.path.append("..") 
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from hintshare.sitemaps import StaticViewSitemap, ArticleSitemap
from . import views
from django.http import HttpResponse

app_name = "stackbase"

sitemaps = {
    'static': StaticViewSitemap,
    'questions':ArticleSitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    # CRUD Function
    path("questions/", views.QuestionListView.as_view(), name="question-lists"),
    path("questions/new/", views.QuestionCreateView.as_view(), name="question-create"),
    path(
        "questions/<int:pk>/",
        views.QuestionDetailView.as_view(),
        name="question-detail",
    ),
    path(
        "questions/<int:pk>/update/",
        views.QuestionUpdateView.as_view(),
        name="question-update",
    ),
    path(
        "questions/<int:pk>/delete/",
        views.QuestionDeleteView.as_view(),
        name="question-delete",
    ),
    path(
        "questions/<int:pk>/comment/",
        views.AddCommentView.as_view(),
        name="question-comment",
    ),
    path("like/<int:pk>", views.like_view, name="like_post"),
    path("like/<int:pk>/<int:id>", views.comment_like_view, name="like_comment"),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
   
]

hintshare/users/models.py
from ast import BinOp
from sched import scheduler
from django.core.files.storage import default_storage as storage
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, ImageField, TextField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from PIL import Image

choices = [("s12", "student grade 12"), ("s11", "student grade 11"), ("t", "teacher")]


class User(AbstractUser):
    """
    Default custom user model for hintshare.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    secondary_email = EmailField(null=True, blank=True)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    bio = TextField(
        _("A quick description of who you are."),
        blank=True,
        max_length=255,
    )
    HL = CharField(_("Your HLs"), blank=True, max_length=255)
    SL = CharField(_("Your SLs"), blank=True, max_length=255)
    Role = CharField(
        _("Role: teacher, student_11, or student_12?"), blank=True, max_length=255
    )

    Image = ImageField(default="default.jpg", upload_to="profile_pic")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(storage.open(self.Image.name))
        img = img.convert('RGB')
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            fh = storage.open(self.Image.name, "wb")
            format = 'jpeg'  # You need to set the correct image format here
            img.save(fh, format)
            fh.close()

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

hintshare/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from allauth.account.utils import has_verified_email, send_email_confirmation
User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

    fields = [
        "bio",
        "Image",
    ]

    widgets = {
        "Image": forms.FileInput(attrs={"class": "input-image-control"}),
    }

    def clean_email(self):
        data = self.cleaned_data["email"]

        if "@surreyschools.ca" not in data:  # any check you need
            # if "@gmail.com" in data:
            #     return data
            raise forms.ValidationError("Must be a surreyschools account")
        # elif "@gmail.com" not in data:  # any check you need
        #     raise forms.ValidationError("Must be a Gmail account")
       
        return data

    class Meta:
        model = User
        exclude = ("user",)


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

hintshare/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.forms import ValidationError
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    # email = object.email
    # email_str = f"https://mail.google.com/mail/?view=cm&fs=1&to=someone@example.com&su=SUBJECT&body=BODY&bcc={email}"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = "nothing"

        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["secondary_email","name", "bio", "Image", "HL", "SL", "Role"]
    success_message = _("Information successfully updated")

    def clean(self):
        data = self.cleaned_data["secondary_email"]
        if "@gmail.com" in data:
            print('gmail')
            return data
    
        elif "@yahoo.com" in data:
            print('yhoo')
            return data
        elif "@hotmail.com" in data:  # any check you need
           print('hot')
           return data
        else:
            print("nothing")
            raise ValidationError("Must be a surreyschools or gmail account")
        return data
    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

hintshare/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
{% load bootstrap_icons %}
{%load static%}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}HintShare: ask questions to your peers.{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A great way to get great advice! Ask your peers questions about homework, study advice, or general life advice. Although it was initially made for IB students, we welcome everybody.">
    <meta name="author" content="Dilreet Raju">
    <link rel="icon" href="{% static 'images/favicons/favicon.png' %}">

    {% block css %}
    {% load static %}
    <!-- Latest compiled and minified Bootstrap CSS -->
       <!-- Latest compiled and minified Bootstrap CSS -->
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
       <!-- Your stuff: Third-party CSS libraries go here -->

       <!-- This file stores project-specific CSS -->
       <link href="{% static 'css/project.css' %}" rel="stylesheet">
       <link href="{% static 'css/carousel.css'%}" rel="stylesheet">


    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
    <!-- Bootstrap JS -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js" integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}


  </head>

  <body class="pt-0 pb-0 mb-0">

    <header class="pt-0 pb-0">

        <nav class="navbar navbar-expand-md navbar-light pl-1" style="background:#F2F5FC;">
          <div class="container-fluid">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand" href="{% url 'stackbase:home' %}"><img style="height: 90px; width: 140px" src="{% static 'images/HintShareLogoFilledIn.svg'%}" alt=""></a>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'stackbase:home' %}"><h6>Home</h6> <span class="visually-hidden">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'AI' %}"><h6>AI Detector</h6></a>
                </li>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'stackbase:question-lists' %}"><h6>View Questions</h6></a>
                </li>

                {% if request.user.is_authenticated %}
                {% if request.user.bio %}
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'stackbase:question-create' %}"><h6>Ask A Question</h6></a>
                </li>
                {%endif%}
                </li>
                
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a class="nav-link" href="{% url 'users:detail' request.user.username  %}"><h6>{% translate "My Profile" %}</h6></a>
                  </li>
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a class="nav-link" href="{% url 'account_logout' %}"><h6>{% translate "Sign Out" %}</h6></a>
                  </li>
                {% else %}

                  {% if ACCOUNT_ALLOW_REGISTRATION %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}"><h6>{% translate "Sign Up" %}</h6></a>
                </li>
                {% endif %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}"><h6>{% translate "Sign In" %}</h6></a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>


    </header>
    <div class="container">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}



    </div> <!-- /container -->

    {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    {% block modal %}{% endblock modal %}
    <!-- Footer -->
    <!-- Footer -->
    {%if not now%}
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start pt-4">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>HintShare
          </h6>
          <p>
           Learn the ropes as you ask questions from seniors who are happy to help.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->

        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#" class="text-reset">Back To Top</a>
          </p>
          <p>
            <a href="{% url 'stackbase:question-create' %}" class="text-reset">Ask A Question</a>
          </p>
          <p>
            <a href="{% url 'stackbase:question-lists' %}" class="text-reset">View Questions</a>
          </p>
          <p>
            <a href="{% url 'account_signup' %}" class="text-reset">Sign Up</a>
          </p>
          <p>
            <a href="{% url 'account_login' %}" class="text-reset">Sign In</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> Surrey, BC, 13153 64 ave</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            dilreetraju@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 778 807 0609</p>
          <p><i class="fas fa-print me-3"></i> + 01 604 356 3123</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright: HintShare

  </div>
  <!-- Copyright -->
</footer>
  {%endif%}
<!-- Footer -->
    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>