config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from stackbase.models import Question
from django.http import HttpResponse
from killgpt.views import TextInputView
info_dict = {
    'queryset': Question.objects.all(),
    'date_field': 'pub_date',
}


urlpatterns = [
    path("", include("stackbase.urls"), name="stackbase"),
    path("AI/", TextInputView, name='AI'),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("hintshare.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("#", TemplateView.as_view(template_name="pages/about.html"), name="profile"),
    path('sitemap.xml', sitemap,
        {'sitemaps': {'questions': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hintshare/users/urls.py
from django.urls import path

from hintshare.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

stackbase/urls.py
import sys
sys.path.append("..") 
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from hintshare.sitemaps import StaticViewSitemap, ArticleSitemap
from . import views
from django.http import HttpResponse

app_name = "stackbase"

sitemaps = {
    'static': StaticViewSitemap,
    'questions':ArticleSitemap,
}

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    # CRUD Function
    path("questions/", views.QuestionListView.as_view(), name="question-lists"),
    path("questions/new/", views.QuestionCreateView.as_view(), name="question-create"),
    path(
        "questions/<int:pk>/",
        views.QuestionDetailView.as_view(),
        name="question-detail",
    ),
    path(
        "questions/<int:pk>/update/",
        views.QuestionUpdateView.as_view(),
        name="question-update",
    ),
    path(
        "questions/<int:pk>/delete/",
        views.QuestionDeleteView.as_view(),
        name="question-delete",
    ),
    path(
        "questions/<int:pk>/comment/",
        views.AddCommentView.as_view(),
        name="question-comment",
    ),
    path("like/<int:pk>", views.like_view, name="like_post"),
    path("like/<int:pk>/<int:id>", views.comment_like_view, name="like_comment"),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
   
]

hintshare/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from allauth.account.utils import has_verified_email, send_email_confirmation
User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

    fields = [
        "bio",
        "Image",
    ]

    widgets = {
        "Image": forms.FileInput(attrs={"class": "input-image-control"}),
    }

    def clean_email(self):
        data = self.cleaned_data["email"]

        if "@surreyschools.ca" not in data:  # any check you need
            # if "@gmail.com" in data:
            #     return data
            raise forms.ValidationError("Must be a surreyschools account")
        # elif "@gmail.com" not in data:  # any check you need
        #     raise forms.ValidationError("Must be a Gmail account")
       
        return data

    class Meta:
        model = User
        exclude = ("user",)


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

stackbase/forms.py
from django import forms

from .models import Comment

OPTIONS = (
    ("l", "likes"),
    ("d", "date created"),
)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["title", "content"]

        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "body": forms.Textarea(attrs={"class": "form-control"}),
        }


class SortForm(forms.Form):
    sort_method = forms.ChoiceField(widget=forms.RadioSelect, choices=OPTIONS)

hintshare/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from django.forms import ValidationError
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    # email = object.email
    # email_str = f"https://mail.google.com/mail/?view=cm&fs=1&to=someone@example.com&su=SUBJECT&body=BODY&bcc={email}"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = "nothing"

        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["secondary_email","name", "bio", "Image", "HL", "SL", "Role"]
    success_message = _("Information successfully updated")

    def clean(self):
        data = self.cleaned_data["secondary_email"]
        if "@gmail.com" in data:
            print('gmail')
            return data
    
        elif "@yahoo.com" in data:
            print('yhoo')
            return data
        elif "@hotmail.com" in data:  # any check you need
           print('hot')
           return data
        else:
            print("nothing")
            raise ValidationError("Must be a surreyschools or gmail account")
        return data
    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

stackbase/views.py
import os

import requests
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import models
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from hintshare.users.models import User

from .forms import CommentForm
from .models import Comment, Question
from django.core.mail import send_mail
from hitcount.views import HitCountDetailView


def home(request):
    questions = Question.objects.all().count()
    users = User.objects.all().count()
    print(questions, users)

    context = {
        "questions": questions,
        "users": users,
    }

    return render(request, "pages/home.html", context)


def about(request):
    return render(request, "about.html")


# CRUD Function
def like_view(request, pk):
    post = get_object_or_404(Question, id=request.POST.get("question_id"))
   
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
        post.total_like = post.total_likes()
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse("stackbase:question-detail", args=[str(pk)]))

# Like function for comments
def comment_like_view(request, pk, id):

    question = get_object_or_404(Question, id=pk)

    post = question.comment.get(id=id)
    print(pk, id)
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
        post.total_like = post.total_likes()
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse("stackbase:question-detail", args=[str(pk)]))

class QuestionListView(ListView):
    model = Question
    context_object_name = "questions"
    ordering = ["-date_created"]
    paginate_by = 8

    # def get_queryset(self):
    #     filter_val = self.request.GET.get('filter', 'give-default-value')
    #     order = self.request.GET.get('orderby', 'give-default-value')
    #     new_context = Question.objects.filter(
    #         title=filter_val,
    #     ).order_by(order)
    #     return new_context

    # def get_context_data(self, **kwargs):
    #     context = super(QuestionListView, self).get_context_data(**kwargs)
    #     context['filter'] = self.request.GET.get('filter', 'give-default-value')
    #     context['orderby'] = self.request.GET.get('orderby', 'give-default-value')
    #     return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get("search-area") or ""
        if search_input:
            # Make sure to come back here to fix the search
            context["questions"] = Question.objects.all().filter(
                title__icontains=search_input
            )
            context["search_input"] = search_input
        
        return context


class QuestionDetailView(DetailView):
    model = Question
    count_hit = True
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        something = get_object_or_404(Question, id=self.kwargs["pk"])
        total_likes = something.total_likes()
        context.update({
        'popular_posts': Question.objects.order_by('-hit_count_generic__hits')[:3],
        })

        liked = False
        if something.likes.filter(id=self.request.user.id).exists():
            liked = True

        context["total_likes"] = total_likes
        context["liked"] = liked
       
        # comment = get_object_or_404(Comment, id=self.kwargs["pk"])
        # print(comment.title)
        # print(comment.total_likes())
        # comment_total_likes = comment.total_likes()

        # comment_liked = False
        # if comment.likes.filter(id=self.request.user.id).exists():
        #     comment_liked = True

        # context["comment_total_likes"] = comment_total_likes
        # context["comment_liked"] = comment_liked
        return context


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    fields = ["title", "content", "tags"]
    context_object_name = "question"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class QuestionUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Question
    fields = ["title", "content"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        questions = self.get_object()
        if self.request.user == questions.user:
            return True
        return False


class QuestionDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Question
    context_object_name = "question"
    success_url = "/"

    def test_func(self):
        questions = self.get_object()
        if self.request.user == questions.user:
            return True
        return False


class CommentDetailView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "stackbase/question-detail.html"

    def form_valid(self, form):
        form.instance.question_id = self.kwargs["pk"]
        return super().form_valid(form)
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        something = get_object_or_404(Comment, id=self.kwargs["pk"])
        total_likes = something.total_likes()

        liked = False
        if something.likes.filter(id=self.request.user.id).exists():
            liked = True

        context["total_likes"] = total_likes
        context["liked"] = liked
    success_url = reverse_lazy("stackbase:question-detail")


class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm

    template_name = "stackbase/question-answer.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.question_id = self.kwargs["pk"]
        question = get_object_or_404(Question, id=self.kwargs["pk"])
        # sender = form.instance.user.get_email_field_name
        sender = "dilreetraju@hintshare.ca"
        reciever = str(question.user.email)
       
        subject = "Hintshare Response"
        message = f"You have recieved a response on your question. Follow this link to view your question and to respond to the comment:"
        send_mail(subject, message, sender,
          [reciever], html_message=f"<html>{message} <a href = 'https://hintshare.ca/questions/{form.instance.question_id}'>See Question!</a></html>")
        try:
            reciever2 = str(question.user.secondary_email)
            send_mail(subject, message, sender,
            [reciever2], html_message=f"<html>{message} <a href = 'https://hintshare.ca/questions/{form.instance.question_id}'>See Question!</a></html>")
        except:
            pass
        # form.instance.send_simple_message()
        # test all of the instance
       
        return super().form_valid(form)

    success_url = reverse_lazy("stackbase:question-lists")

hintshare/templates/stackbase/question_detail.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap_icons %}
{% load hitcount_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap"
        rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->

</head>

<body style='background: linear-gradient(to bottom, #F2F5FC 6%, #000099 96%)'>
    <div class="container pt-5">
        <div id="sub-nav">
            <!-- <h1 id="fh1">Hey Guys, Let's help :)</h1> -->
            <!-- <button class="btn" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button> -->

            <!-- <div style="margin-top: 55px;">
                <button class="btn btn-primary" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button>
            </div> -->
        </div>
        <div class="list-question">
            <div class="page_obj m-2">



                <div class="container col-12 col-md-8 col-lg-8 border border-dark px-2 bg-white rounded">
                    <div class="row pt-2">
                        <div
                            class=" mh-25 h-md-0 d-flex flex-row flex-sm-column col-sm-2 justify-content-between justify-content-sm-start">
                        {% if user.bio%}
                            <a href="{% url 'users:detail' question.user  %}"><img src="{{ question.user.Image.url }}"
                                class="img-fluid mh-25 rounded-circle pd-3 img-thumbnail border border-primary"
                                style="height: 75px; width: 75px;" alt="..."></a>
                        {% else %}
                            <a href="{% url 'users:detail' question.user  %}"><img src="{{ question.user.Image.url }}"
                                class="img-fluid mh-25 rounded-circle pd-3 img-thumbnail border border-primary"
                                style="height: 75px; width: 75px;" alt="..."></a>
                        {% endif %}
                            <form class='pt-3' action="{% url 'stackbase:like_post' object.pk %}" method="POST">
                                {% csrf_token %}
                                {% if user.is_authenticated %}
                                {% if liked %}
                                
                                    <button class='bg-danger border border-danger' type="submit" name="question_id"
                                        value="{{ question.id }}">
                                        <div class="mt-sm-3 m-1 pl-2  bg-danger text-white text-center rounded">
                                            <div class="container px-2 pt-1">{% bs_icon 'hand-thumbs-down' color='white' size='1.5em'%}</div>
                                            <h5 class="p-2 mx-2"> {{ question.total_likes }}</h5>
                                        </div>
                                    </button>
                               

                                {% else %}
                                <div style="display: flex; align-items: center; margin-left: 10px;">
                                    <button type="submit" name="question_id" value="{{ question.id }}"
                                        style="border: none; border-radius: 30px;">
                                        <div
                                            class="mt-sm-3 m-1 pl-2 border border-success bg-success text-white text-center rounded">
                                            <div class="container px-2 pt-1">{% bs_icon 'hand-thumbs-up' color='white' size='1.5em'%}</div>
                                            <h5 class="p-2 mx-2"> {{ question.total_likes }}</h5>
                                        </div>
                                    </button>

                                </div>
                                {% endif %}
                                {% else %}
                                <h5 style="margin-left: 10px; cursor: pointer;"><a href="#">Login</a> to Like Question | {{ total_likes }} Likes</h5>
                                
                                {% endif %}

                            </form>


                        </div>
                        <div class="col-12 col-sm-10 pl-2" style="height:400px;">
                            <div class="d-flex">
                                {% if user.is_authenticated %}
                                <div class="p-2"><a href="{% url 'users:detail' question.user  %}">{{question.user}}</a>
                                </div>
                                {%else%}
                                <div class="p-2"><a href="{% url 'account_signup'  %}">{{question.user}}</a>
                                </div>
                                {%endif%}
                                <div class="p-2">
                                    <div class='container rounded bg-success text-white'>{{question.tags}}</div>
                                </div>


                                <div class="p-2">
                                    <h6>On: <a
                                            href="{% url 'stackbase:question-detail' question.id%}">{{question.date_created|date:"j, F, Y"}}</a></h6>
                                </div>
                            </div>
                            <h3 class=pt-5 id="fh3">{{ question.title }}</h3>
                            <hr>
                            <div class="container pd-5">
                                <h6 id="fh6" style="text-align: left;  color: rgba(54, 54, 54, 0.852);">
                                    {{question.content|safe}} </h6>
                            </div>

                        </div>
                    </div>
                    <hr>
                    {% if user.bio %}
                    <a href="{% url 'stackbase:question-comment' question.id %}">
                        <div class="container btn btn-primary">Answer Question </div>
                    </a>
                    {%else%}
                    <a href="{% url 'account_signup' %}">
                        <div class="container btn btn-primary">Sign Up and Make Bio To Answer Question </div>
                    </a>
                    {%endif%}
                    <hr>
                    <div class="container m-2">

                        <a style="text-decoration: none; " class="btn btn-dark"
                            href="{% url 'stackbase:question-lists' %}">Report</a>
                        {%if user == question.user%}
                        <a style="text-decoration: none; " class="btn btn-outline-success"
                            href="{% url 'stackbase:question-update' question.id %}">Edit</a>
                        <a style="text-decoration: none; " class="btn btn-outline-danger"
                            href="{% url 'stackbase:question-delete' question.id %}">Delete</a>
                        {% endif %}
                        <a style="text-decoration: none; " class="btn btn-outline-secondary"
                            href="{% url 'stackbase:question-lists' %}">Go Back</a>
                    </div>
                    <!-- Question ends here  -->
                    <div class="container py-2">
                        <h2 class='m-1'>Answers...</h2> <br><br><br>
                <!-- No comments -->
                {% if not question.comment.all %}
                <h3 class='m-5'>No Answers yet... <a href="{% url 'stackbase:question-comment' question.id %}">Answer
                        Question</a> </h3>
                {% else %}
                <!-- if comments -->
                {% for comment in question.comment.all %}
                <hr>
           
                    <div class="row  ">
                        <div
                            class="  h-md-0 d-flex flex-row flex-sm-column col-sm-2 justify-content-between justify-content-sm-start">
                        {% if user.bio %}
                            <a href="{% url 'users:detail' comment.user  %}"><img src="{{ comment.user.Image.url }}"
                                class="img-fluid mh-25 rounded-circle pd-3 img-thumbnail border border-primary"
                                style="height: 75px; width: 75px;" alt="..."></a>
                            {%else%}
                            <a href="{% url 'account_signup' %}"><img src="{{ comment.user.Image.url }}"
                                class="img-fluid mh-25 rounded-circle pd-3 img-thumbnail border border-primary"
                                style="height: 75px; width: 75px;" alt="..."></a>
                            {%endif%}
                                <form action="{% url 'stackbase:like_comment' object.pk comment.id %}" method="POST">
                                    {% csrf_token %}
                                    {% if user.is_authenticated %}
                                        {%for obj in comment.likes.all%}
                                            {% if user == obj %}
                                                <div  class ='pt-3'style="display: flex; align-items: center; margin-left: 10px;">
                                                    <button type="submit" name="comment_id" value="{{ comment.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> 
                                                </div>
                                            {% else %}
                                              
                                            {% endif %}
                                            {% endfor %}
                                            <div style="display: flex; align-items: center; margin-left: 10px;">
                                                <button type="submit" name="comment_id" value="{{ comment.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{comment.likes.all| length }}  Likes</h5>
                                            </div>
                                        {% else %}
                                            <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'account_signup' %}">Login</a> to Like Comment |  {{ total_likes }} Likes</h5>
                                    
                                     {% endif %}
                                </form>

                        </div>
                        {% if user.bio %}
                        <div class="col-12 col-sm-10 pl-2">
                            <div class="d-flex">
                                <div class="p-2">Answered by: <a href="{% url 'users:detail' comment.user  %}">{{comment.user}}</a>
                                </div>
                            {%else%}
                            <div class="col-12 col-sm-10 pl-2" style="height:400px;">
                                <div class="d-flex">
                                    <div class="p-2">Answered by: <a href="{% url 'account_signup' %}">{{comment.user}}</a>
                                    </div>
                                {% endif %}
                               


                                <div class="p-2">
                                    <h6>On: <a href="{% url 'stackbase:question-detail' question.id%}">{{comment.date_created|date:"j, F, Y"}}</a></h6>
                                </div>
                            </div>
                            <h3 class=pt-2 id="fh3">{{ comment.title }}</h3>
                            <hr>
                            <div class="container pd-5">
                                <h6 id="fh6" style="text-align: left;  color: rgba(54, 54, 54, 0.852);">
                                    {{comment.content|safe}} </h6>
                            </div>

                        </div>
                        {% endfor %}
                        {% endif %}


                    </div>



                </div>
          
        </div> <br>

        
 
             
               
                <hr>
               




            </div> <br><br>
            <!-- Answer Section -->

        </div> <br>
    </div>
    </div>
    <br>

    </div>
</body>

</html>
{% endblock content %}

hintshare/templates/stackbase/question_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<main role="main" style ='background: linear-gradient(to bottom right, #000099 0%, #339966 114%);'>

    {%if not prediction%}
    <div class="container py-5" style ='background:linear-gradient(to bottom right, #000099 0%, #339966 114%)'>
        <div class ='col-md-8 offset-md-2 pt-5 bg-white rounded border'>
            <h1 class = 'py-4 display-1 text-success m-5 ' > Ask <span class="text-black" id='Titlefont'>Your Question</h1>

            <hr class="">
            <h4 class="p-2 m-3 py-4" style="color:#012970">Make sure to respect IB's Collusion Policies, and make sure not to do anything that will incriminate you.</h4>
            <hr class="">
            <div class= 'container p-5'>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form|crispy }}
                    <button class="btn btn-success" id="logout-btn" type="submit">Post Question</button>
                    <a style="text-decoration: none; " class="btn btn-outline-secondary" href="">Cancel</a>
                  </form>

                  {% endif%}


            </div>
        </div>



    </div>
</main>

{% endblock content %}